name       : i3
version    : 4.20
release    : 44
source     :
    - https://github.com/Airblader/i3/releases/download/4.20/i3-4.20.tar.xz : 01815c98bcf14f2a8856fbe95bafa3e91ff249af216500d96ddc983533d51274
    - https://github.com/i3-gnome/i3-gnome/archive/refs/tags/40.4.tar.gz : 8cf578390ce98b4f7c14d7f49ce4eb2f7255119a685c99ded68b276521ab25f4
license    :
    - BSD-3-Clause # i3
    - MIT # i3-gnome Integration
component  : desktop.i3
summary    : A better tiling and dynamic window manager. This uses the i3-gaps fork.
description: |
    A better tiling and dynamic window manager. This uses the i3-gaps fork.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - alsa-utils
    - dmenu
    - i3lock
    - i3status
    - light
    - perl-anyevent
    - perl-json-xs
    - playerctl
    - polkit-gnome
    - scrot
setup      : |
    tar xf $sources/40.4.tar.gz
    %patch -p1 < $pkgfiles/0001-Implement-statelessness.patch
    %meson_configure
    cd AnyEvent-I3
    perl Makefile.PL
build      : |
    %ninja_build
    cd AnyEvent-I3
    %make
install    : |
    %ninja_install
    pushd AnyEvent-I3
    %make_install
    popd

    # Install our configuration for better integration
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config.keycodes
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config
    install -Dm00755 $pkgfiles/i3-dbus $installdir/usr/bin/i3-dbus
    sed 's:Exec=i3:Exec=i3-dbus:g' -i $installdir/usr/share/xsessions/i3.desktop

    # Install GNOME Integration
    pushd $workdir/i3-gnome-40.4
        %make_install
    popd
