name       : i3
version    : 4.15.0.1
release    : 26
source     :
    - https://github.com/Airblader/i3/archive/4.15.0.1.tar.gz : 543998c0cc2a7f7ec7dfe849bc85cbadb442ce2286f34d7afc437a346d5c469b
license    : BSD-3-Clause
component  : desktop.i3
summary    : A better tiling and dynamic window manager. This uses the i3-gaps fork.
description: |
    A better tiling and dynamic window manager. This uses the i3-gaps fork.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - alsa-utils
    - dmenu
    - i3lock
    - i3status
    - light
    - playerctl
    - polkit-gnome
    - scrot
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-statelessness.patch
    %reconfigure
    mkdir build && cd build/
    ../%configure --disable-sanitizers
build      : |
    %make -C build
install    : |
    %make_install -C build
    # Install our configuration for better integration
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config.keycodes
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config
    install -Dm00755 $pkgfiles/i3-dbus $installdir/usr/bin/i3-dbus
    sed 's:Exec=i3:Exec=i3-dbus:g' -i $installdir/usr/share/xsessions/i3.desktop
