name       : i3
version    : 4.18.1
release    : 37
source     :
    - https://github.com/Airblader/i3/releases/download/4.18.1/i3-4.18.1.tar.bz2 : 33a9c5d4922c9dd7585a201a982a9113d670ff72e9550f242c1985fb5bd6bcb3
    - https://github.com/i3-gnome/i3-gnome/archive/3.36.0.tar.gz : 668fd00c0a361682516ca9cd7abe995b99f1db486bf3631910d6be38d0fd61b6
license    :
    - BSD-3-Clause # i3
    - MIT # i3-gnome Integration
component  : desktop.i3
summary    : A better tiling and dynamic window manager. This uses the i3-gaps fork.
description: |
    A better tiling and dynamic window manager. This uses the i3-gaps fork.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - alsa-utils
    - dmenu
    - i3lock
    - i3status
    - light
    - perl-anyevent
    - perl-json-xs
    - playerctl
    - polkit-gnome
    - scrot
setup      : |
    tar xf $sources/3.36.0.tar.gz
    %patch -p1 < $pkgfiles/0001-Implement-statelessness.patch
    %reconfigure
    mkdir build && cd build/
    ../%configure --disable-sanitizers
    cd ../AnyEvent-I3
    perl Makefile.PL
build      : |
    %make -C build
    cd AnyEvent-I3
    %make
install    : |
    %make_install -C build
    cd AnyEvent-I3
    %make_install

    # Install our configuration for better integration
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config.keycodes
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config
    install -Dm00755 $pkgfiles/i3-dbus $installdir/usr/bin/i3-dbus
    sed 's:Exec=i3:Exec=i3-dbus:g' -i $installdir/usr/share/xsessions/i3.desktop

    # Install GNOME Integration
    pushd $workdir/i3-gnome-3.36.0
        %make_install
    popd
