name       : i3
version    : 4.13
release    : 19
source     :
    - https://github.com/Airblader/i3/archive/4.13.tar.gz : e80c07e525a07f2d3d2f02d282774d3264b6d1f165713c9903c06626ba4d2571
license    : BSD-3-Clause
component  : desktop.i3
summary    : A better tiling and dynamic window manager
description: |
    A better tiling and dynamic window manager
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - alsa-utils
    - dmenu
    - i3lock
    - i3status
    - light
    - playerctl
    - polkit-gnome
    - scrot
setup      : |
    autoreconf -vfi
    mkdir build && cd build/
    ../%configure --disable-static --disable-sanitizers
build      : |
    cd build/
    %make
install    : |
    cd build/
    %make_install
    # Install our configuration for better integration
    install -Dm00644 $pkgfiles/config $installdir/etc/i3/config.keycodes
    install -Dm00644 $pkgfiles/config $installdir/etc/i3/config
    install -Dm00755 $pkgfiles/i3-dbus $installdir/usr/bin/i3-dbus
    sed 's:Exec=i3:Exec=i3-dbus:g' -i $installdir/usr/share/xsessions/i3.desktop
