name       : i3
version    : 4.12
release    : 5
source     :
    - https://github.com/Airblader/i3/archive/4.12.tar.gz : 1aad4c5e4da8a0f5895216393f728fb25e7d5959f97d113873054dc5464a34c5
license    : BSD-3-Clause
component  : desktop
summary    : A better tiling and dynamic window manager
description: |
    A better tiling and dynamic window manager
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - alsa-utils
    - dmenu
    - i3lock
    - i3status
    - playerctl
    - scrot
    - xbacklight
setup      : |
    %patch -p1 < $pkgfiles/fix-out-of-tree-build.patch
build      : |
    %make
install    : |
    %make_install
    # Install our configuration for better integration
    install -Dm00644 $pkgfiles/config.keycodes $installdir/etc/i3/config.keycodes