name       : i3
version    : 4.12
release    : 3
source     :
    - http://i3wm.org/downloads/i3-4.12.tar.bz2 : e19e1ce08c2549cba83e083cc768d487202c41760d5c283f67752e791f1d78b4
license    : BSD-3-Clause
component  : desktop
summary    : A better tiling and dynamic window manager
description: |
    A better tiling and dynamic window manager
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - dmenu
    - i3lock
    - i3status
    - xbacklight
build      : |
    %make
install    : |
    %make_install
