name       : i3
version    : 4.14.1
release    : 24
source     :
    - https://github.com/Airblader/i3/archive/4.14.1.tar.gz : 47a226a5a750a6146ad47d56a7a45d7d71fea18e833b6b9565f45205c99bd685
license    : BSD-3-Clause
component  : desktop.i3
summary    : A better tiling and dynamic window manager. This uses the i3-gaps fork.
description: |
    A better tiling and dynamic window manager. This uses the i3-gaps fork.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libpcre)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pango)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-xrm)
    - pkgconfig(xcb-util)
    - pkgconfig(xkbcommon-x11)
    - pkgconfig(yajl)
    - asciidoc
    - docbook-xml
    - libev-devel
    - perl
    - xmlto
rundeps    :
    - alsa-utils
    - dmenu
    - i3lock
    - i3status
    - light
    - playerctl
    - polkit-gnome
    - scrot
setup      : |
    %patch -p1 < $pkgfiles/0001-Implement-statelessness.patch
    autoreconf -vfi
    mkdir build && cd build/
    ../%configure --disable-sanitizers
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
    # Install our configuration for better integration
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config.keycodes
    install -Dm00644 $pkgfiles/config $installdir/usr/share/defaults/i3/config
    install -Dm00755 $pkgfiles/i3-dbus $installdir/usr/bin/i3-dbus
    sed 's:Exec=i3:Exec=i3-dbus:g' -i $installdir/usr/share/xsessions/i3.desktop
